replicaCount: 1

# In DevOps approach, the tag is often tied to the environment and we often use the commit hash or a version number.
image:
  repository: noreddinelam/gitops # Ensure this matches your Docker repository
  pullPolicy: IfNotPresent
  tag: dev-1.0.0 # Update this tag as needed

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: gitops.dev.learn.com
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

resources: { }

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 30

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 30

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: [ ]

volumeMounts: [ ]

nodeSelector: { }

tolerations: [ ]

affinity: { }

app:
  profile: dev

database:
  username: postgres
  url: jdbc:postgresql://gitops-postgres-postgresql:5432/gitops-dev
