apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-learn-dev
  namespace: argocd
spec:
  project: gitops-learn
  source:
    repoURL: https://github.com/noreddinelam/gitops.git # Ensure this URL matches your repository
    targetRevision: dev
    path: gitops-learn
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
