apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-learn-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/noreddinelam/gitops.git
    targetRevision: staging
    path: gitops-learn
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
